server:
  port: 9090

# dubbo springboot 配置
dubbo:
  application:
    name: boot-core
  registry:
    address: zookeeper://127.0.0.1:2181
  protocol:
    name: rmi
    port: 11889
  provider:
    timeout: 1000
  scan:
    base-packages: com.sgcai.boot.service

spring:
    application:
       name: boot-core
    datasource:
       type: com.alibaba.druid.pool.DruidDataSource    # 配置当前要使用的数据源的操作类型
       driver-class-name: com.mysql.jdbc.Driver        # 配置MySQL的驱动程序类
       url: jdbc:mysql://localhost:3306/cn_cancan_user?useUnicode=true&characterEncoding=utf8&tinyInt1isBit=false        # 数据库连接地址
       username: root                                  # 数据库用户名
       password: 123456                                # 数据库连接密码
       dbcp2:                                          # 进行数据库连接池的配置
       min-idle: 5                                   # 数据库连接池的最小维持连接数
       initial-size: 5                               # 初始化提供的连接数
       max-total: 5                                  # 最大的连接数
       max-wait-millis: 200                            # 等待连接获取的最大超时时间
    redis:
      host: 127.0.0.1
      port: 6379
      jedis:
        pool:
          max-active: 20
          max-idle: 8
          min-idle: 1




mybatis:
  type-aliases-package: com.sgcai.boot.core.bootcore     # 定义所有操作类的别名所在包
  mapper-locations:                                     # 所有的mapper映射文件
  - classpath:mapper/**/*.xml